@tool
class_name AttributeSetGeneratorScript
extends EditorScript

const CONFIG_PATH := "res://logic-game-framework-config/attributes/attributes_config.gd"
const OUTPUT_DIR := "res://logic-game-framework-config/attributes/generated"
const EXAMPLE_CONFIG_PATH := "res://addons/logic-game-framework/example/attributes/attributes_config.gd"
const EXAMPLE_OUTPUT_DIR := "res://addons/logic-game-framework/example/attributes/generated"
const _SHADOWED_GLOBAL_IDENTIFIERS := ["range", "min", "max", "clamp"]

func _run() -> void:
	print("[LGF] Attribute generation started")
	var generated: Array[String] = []
	if _generate_from_config(CONFIG_PATH, OUTPUT_DIR):
		generated.append("project")
	if _generate_from_config(EXAMPLE_CONFIG_PATH, EXAMPLE_OUTPUT_DIR):
		generated.append("example")

	if generated.is_empty():
		push_error("No attribute sets were generated")
		return
	print("[LGF] Attribute sets generated for: %s" % ", ".join(generated))

func _generate_from_config(config_path: String, output_dir: String) -> bool:
	if not ResourceLoader.exists(config_path):
		push_error("AttributesConfig not found: %s" % config_path)
		return false
	print("[LGF] Generating from %s -> %s" % [config_path, output_dir])
	var config: GDScript = load(config_path) as GDScript
	if config == null:
		push_error("AttributesConfig not found: %s" % config_path)
		return false

	var sets: Dictionary = config.SETS
	if typeof(sets) != TYPE_DICTIONARY:
		push_error("AttributesConfig.SETS must be Dictionary: %s" % config_path)
		return false

	var dir := DirAccess.open("res://")
	if dir == null:
		push_error("Failed to open res://")
		return false

	var result := dir.make_dir_recursive(output_dir)
	if result != OK:
		push_error("Failed to create output dir: %s" % output_dir)
		return false

	var set_names: Array[String] = []
	for key: String in sets.keys():
		set_names.append(key)
	set_names.sort()

	for set_name in set_names:
		var attr_defs: Variant = sets[set_name]
		if typeof(attr_defs) != TYPE_DICTIONARY:
			push_error("Attribute set %s must be Dictionary" % set_name)
			continue
		_generate_set(set_name, attr_defs as Dictionary, output_dir)

	print("Generated %d sets from %s" % [set_names.size(), config_path])
	return true

func _generate_set(set_name: String, attr_defs: Dictionary, output_dir: String) -> void:
	var set_class_name := "%sAttributeSet" % set_name
	var file_name := _to_snake_case(set_class_name)
	var file_path := "%s/%s.gd" % [output_dir, file_name]
	var lines: Array[String] = []

	# 分离基础属性和派生属性
	var base_attrs: Dictionary = {}
	var derived_attrs: Dictionary = {}
	for attr_name: String in attr_defs.keys():
		var cfg: Dictionary = attr_defs[attr_name]
		if cfg.has("derived"):
			derived_attrs[attr_name] = cfg
		else:
			base_attrs[attr_name] = cfg

	# 文件头警告
	lines.append("## ⚠️ AUTO-GENERATED FILE - DO NOT MODIFY")
	lines.append("## Generated by AttributeSetGeneratorScript")
	lines.append("")
	lines.append("extends BaseGeneratedAttributeSet")
	lines.append("class_name %s" % set_class_name)
	lines.append("")
	lines.append("")
	lines.append("func _init(p_actor_id: String = \"\") -> void:")
	lines.append("\tsuper(p_actor_id)")
	lines.append("\t_raw.apply_config({")
	
	# 只为基础属性生成 _raw 配置
	var base_attr_names: Array[String] = []
	for key: String in base_attrs.keys():
		base_attr_names.append(key)
	base_attr_names.sort()
	for attr_name in base_attr_names:
		var attr_key := attr_name
		var cfg: Dictionary = base_attrs[attr_name]
		var line := "\t\t\"%s\": { \"baseValue\": %s" % [attr_key, _value_to_string(cfg.get("baseValue", 0.0))]
		if cfg.has("minValue") and cfg["minValue"] != null:
			line += ", \"minValue\": %s" % _value_to_string(cfg["minValue"])
		if cfg.has("maxValue") and cfg["maxValue"] != null:
			line += ", \"maxValue\": %s" % _value_to_string(cfg["maxValue"])
		line += " },"
		lines.append(line)

	lines.append("\t})")
	lines.append("")
	
	# 生成基础属性的访问器
	for attr_name in base_attr_names:
		var attr_key := attr_name
		var safe_key: String = _escape_identifier(attr_key)
		var snake_case_key: String = _to_snake_case(attr_key)
		lines.append("")
		lines.append("var %s: float:" % safe_key)
		lines.append("\tget:")
		lines.append("\t\treturn _raw.get_current_value(\"%s\")" % attr_key)
		lines.append("var %s_breakdown: AttributeBreakdown:" % safe_key)
		lines.append("\tget:")
		lines.append("\t\treturn _raw.get_breakdown(\"%s\")" % attr_key)
		lines.append("func get_%s_breakdown() -> AttributeBreakdown:" % snake_case_key)
		lines.append("\treturn _raw.get_breakdown(\"%s\")" % attr_key)
		lines.append("const %s_attribute := \"%s\"" % [safe_key, attr_key])

		lines.append("func set_%s_base(value: float) -> void:" % snake_case_key)
		lines.append("\t_raw.set_base(\"%s\", value)" % attr_key)
		lines.append("func on_%s_changed(callback: Callable) -> Callable:" % snake_case_key)
		lines.append("\tvar wrapper := func(raw_event: Dictionary) -> void:")
		lines.append("\t\tif raw_event.get(\"attributeName\", \"\") == \"%s\":" % attr_key)
		lines.append("\t\t\tcallback.call(GameEvent.AttributeChanged.create(")
		lines.append("\t\t\t\tactor_id,")
		lines.append("\t\t\t\traw_event.get(\"attributeName\", \"\"),")
		lines.append("\t\t\t\traw_event.get(\"oldValue\", 0.0),")
		lines.append("\t\t\t\traw_event.get(\"newValue\", 0.0),")
		lines.append("\t\t\t))")
		lines.append("\t_raw.add_change_listener(wrapper)")
		lines.append("\treturn func() -> void:")
		lines.append("\t\t_raw.remove_change_listener(wrapper)")
	
	# 生成派生属性的只读访问器
	var derived_attr_names: Array[String] = []
	for key: String in derived_attrs.keys():
		derived_attr_names.append(key)
	derived_attr_names.sort()
	if not derived_attr_names.is_empty():
		lines.append("")
		lines.append("# ========== Derived Attributes (read-only) ==========")
	
	for attr_name in derived_attr_names:
		var attr_key := attr_name
		var safe_key: String = _escape_identifier(attr_key)
		var snake_case_key: String = _to_snake_case(attr_key)
		var cfg: Dictionary = derived_attrs[attr_name]
		var derived_cfg: Dictionary = cfg["derived"]
		var expr := _build_derived_expression(derived_cfg)
		
		if expr.is_empty():
			push_error("Invalid derived config for '%s'" % attr_key)
			continue
		
		lines.append("")
		lines.append("## Derived: %s" % _derived_config_to_comment(derived_cfg))
		lines.append("var %s: float:" % safe_key)
		lines.append("\tget:")
		lines.append("\t\treturn %s" % expr)
		lines.append("func get_%s() -> float:" % snake_case_key)
		lines.append("\treturn %s" % expr)

	var file := FileAccess.open(file_path, FileAccess.WRITE)
	if file == null:
		push_error("Failed to write file: %s" % file_path)
		return
	file.store_string("\n".join(lines) + "\n")
	file.close()


## 构建派生属性的表达式
## 支持: { "op": "sub", "left": "max_hp", "right": "damage" }
## 支持: { "op": "mul", "left": "strength", "right": 2.5 }
func _build_derived_expression(cfg: Dictionary) -> String:
	if not cfg.has("op") or not cfg.has("left") or not cfg.has("right"):
		push_error("Derived config must have 'op', 'left', 'right': %s" % str(cfg))
		return ""
	
	var op: String = cfg["op"]
	var left: Variant = cfg["left"]
	var right: Variant = cfg["right"]
	
	var left_expr := _operand_to_expression(left)
	var right_expr := _operand_to_expression(right)
	
	if left_expr.is_empty() or right_expr.is_empty():
		return ""
	
	match op:
		"sub":
			return "%s - %s" % [left_expr, right_expr]
		"mul":
			return "%s * %s" % [left_expr, right_expr]
		_:
			push_error("Unsupported derived op: %s" % op)
			return ""


## 将操作数转换为表达式
## 字符串 -> 属性引用 (self.xxx)
## 数字 -> 常量
func _operand_to_expression(operand: Variant) -> String:
	match typeof(operand):
		TYPE_STRING:
			# 属性引用
			var safe_key := _escape_identifier(operand)
			return safe_key
		TYPE_INT, TYPE_FLOAT:
			# 常量
			return str(operand)
		_:
			push_error("Invalid operand type: %s" % str(operand))
			return ""


## 将派生配置转换为注释字符串
func _derived_config_to_comment(cfg: Dictionary) -> String:
	var op: String = cfg.get("op", "?")
	var left: Variant = cfg.get("left", "?")
	var right: Variant = cfg.get("right", "?")
	
	var op_symbol := "?"
	match op:
		"sub": op_symbol = "-"
		"mul": op_symbol = "*"
	
	return "%s %s %s" % [str(left), op_symbol, str(right)]

func _escape_identifier(name: String) -> String:
	if _SHADOWED_GLOBAL_IDENTIFIERS.has(name):
		return "%s_" % name
	return name

func _to_snake_case(pascal_case: String) -> String:
	# 如果已经包含下划线，假定已经是 snake_case
	if "_" in pascal_case:
		return pascal_case.to_lower()
	
	var result := ""
	for i in range(pascal_case.length()):
		var c := pascal_case[i]
		# 在大写字母前添加下划线（除了第一个字符）
		if c == c.to_upper() and c.to_lower() != c and i > 0:
			result += "_"
		result += c.to_lower()
	return result

func _value_to_string(value: Variant) -> String:
	match typeof(value):
		TYPE_STRING:
			return "\"%s\"" % value.c_escape()
		TYPE_BOOL:
			return "true" if value else "false"
		TYPE_INT, TYPE_FLOAT:
			return str(value)
		TYPE_NIL:
			return "null"
		_:
			return str(value)
